Add Checkbox tests
rbrtsmith/nebula-react pull request #2
Opened 2017-08-08 12:06 UTC by kwood15

Please look over this and refactor me ta

2017-08-08 12:29 UTC, rbrtsmith requested changes

2017-08-08 12:29 UTC, rbrtsmith commented on src/components/Form/CheckboxInput.jsx
> +import { classNames } from '../../utils/'
Good

2017-08-08 12:29 UTC, rbrtsmith commented on src/components/Form/CheckboxInput.jsx
> +  <input className={classNames('c-form-input__input', className)} {...rest} />
Good

2017-08-08 12:29 UTC, rbrtsmith commented on src/components/Form/CheckboxInput.jsx
> +const CheckboxInput = ({ className, ...rest }) => (
Lets just call it `Checkbox`

2017-08-08 12:29 UTC, rbrtsmith commented on src/components/Form/CheckboxInput.jsx
> +)
We're missing some bits of the checkbox.  In nebula it's hidden away and always comes with the associated label to style it etc.
![screen shot 2017-08-08 at 13 27 46](https://user-images.githubusercontent.com/4982001/29071889-6a3db0d2-7c3d-11e7-9995-20dba75b610d.png)

HTML from Nebula Components:
```html
<div class="c-form-input">
  <input type="checkbox" class="c-form-input__input" id="check-1" value="on">
   <label for="check-1" class="c-form-input__label c-form-input__label--checkbox">
      Select
   </label>
</div>
```

2017-08-08 17:26 UTC, kwood15 commented
Have refactored the checkboxes and added tests for the additional elements - 1 test currently broken so we can over this tmw if you like?

2017-08-11 12:25 UTC, kwood15 commented
Have refactored the tests and have added to demo so please review. Screenshot here:

![screen shot 2017-08-11 at 13 22 43](https://user-images.githubusercontent.com/11405108/29212857-8401972e-7e98-11e7-9952-94280c8f9e13.png)

2017-08-11 12:47 UTC, rbrtsmith requested changes
Really good work so far.  Just a few things need fixing then this is good to merge in.

2017-08-11 12:47 UTC, rbrtsmith commented on src/components/Form/__tests__/Checkbox.jsx
> +import React from 'react'
This test file is testing `CheckboxWrapper` and not `Checkbox`

2017-08-11 12:47 UTC, rbrtsmith commented on src/components/Form/Label.jsx
> +  <label id="c-label" htmlFor={htmlFor} className={classNames('c-label', className)} {...rest}>
Hard coded `id`.  Label's don't need an `id` so just let it be optionally passed with `...rest`

2017-08-11 12:47 UTC, rbrtsmith commented on src/components/Form/__tests__/CheckboxWrapper.jsx
> +  it('renders children', () => {
Let's test that children get rendered in the correct order like in `RadioWrapper` as the ordering is critical for functionality.

2017-08-11 12:47 UTC, rbrtsmith commented on src/components/Form/__tests__/Label.jsx
> +    const $ = shallow(<Form.Label id="foo" htmlFor="t" />)
This test still passes despite `id` in `Label` being hard coded as the `...rest` spread in `Label` overrides it.  You can just remove the `id` prop from `Label`

2017-08-11 14:08 UTC, kwood15 commented on src/components/Form/__tests__/Checkbox.jsx
> +import React from 'react'
Done

2017-08-11 14:11 UTC, kwood15 commented on src/components/Form/Label.jsx
> +  <label id="c-label" htmlFor={htmlFor} className={classNames('c-label', className)} {...rest}>
Done

2017-08-11 14:12 UTC, kwood15 commented on src/components/Form/__tests__/CheckboxWrapper.jsx
> +  it('renders children', () => {
Done on the Checkbox test

2017-08-11 14:15 UTC, kwood15 commented on src/components/Form/__tests__/Label.jsx
> +    const $ = shallow(<Form.Label id="foo" htmlFor="t" />)
Done

2017-08-11 14:25 UTC, kwood15 commented
Have fixed the above

2017-08-11 14:29 UTC, rbrtsmith approved these changes

2017-08-11 14:29 UTC, merged